### ISSUE TITLE
The weird dropdown issue

### ISSUE THREAD

**Issue by thefatoneinthecorner** [GregHila/primeng-angular-cli#1]
Many thanks for this project, it inspired me to investigate using the angular-cli with PrimeNG.

Your problem with the drop down is caused by PrimeNG not seeing its required styles.

I used angular-cli 1.0.0-beta.19.3 and had exactly the same problem as you. This version of the cli will generate an empty src/styles.css file. Add the following lines to fix the problem:

`@import '../node_modules/primeng/resources/primeng.min.css';`
` @import '../node_modules/primeng/resources/themes/omega/theme.css'; `

**Comment by GAHila** [comment]
Thank you. That corrected the issue.
